TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += indfurn.db
DB += indfurn_pid.db
DB += indfurn_thermocouple_faults.db
DATA += indfurn.proto

#=======================================
include $(TOP)/configure/RULES
